maxLoginAttemptTimePeriodInMins = 10
#maxNumberOfUnsuccessfulClientIpAttempt 
maxNumberOfUnsuccessfulLoginAttempt = 3 
#numberOfLastMinsToCountLastLoginAttemptByClientIp 
  numberOfDaysToExpirePassword = 120 
  numberOfDaysToNotifyUserOfPasswordExpiration = 10
  numberOfMinsToExpireSelfResetTempPassword = 15 
  numberOfDaysToExpireNonVendorTempPassword = 7 
  numberOfDaysToExpireVendorTempPassword = 5 
  numberOfDaysToExpireTempPwd = 5 
  maxUserInactivityTimeInMins = 20 
  timeToRenewTokenInMins = 5 
  numberOfDaysToDisableAccount = 121 
  numberOfDaysToRemoveAccount = 243 
