package gov.treas.fms.services.tcsonline_3_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-01-23T19:59:31.386-06:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "TCSOnlineService_3_0", 
                  wsdlLocation = "file:/C:/Users/MHussaini/AmerImportantFiles/spring-webservices-tutorial-master/src/main/resources/wsdl7.7_3.0_TCSOnlineService/TCSOnlineService.wsdl",
                  targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0") 
public class TCSOnlineService30 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fms.treas.gov/services/tcsonline_3_0", "TCSOnlineService_3_0");
    public final static QName TCSOnlineServicePort = new QName("http://fms.treas.gov/services/tcsonline_3_0", "TCSOnlineServicePort");
    public final static QName TCSOnlineServicePort0 = new QName("http://fms.treas.gov/services/tcsonline_3_0", "TCSOnlineServicePort.0");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/MHussaini/AmerImportantFiles/spring-webservices-tutorial-master/src/main/resources/wsdl7.7_3.0_TCSOnlineService/TCSOnlineService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TCSOnlineService30.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/MHussaini/AmerImportantFiles/spring-webservices-tutorial-master/src/main/resources/wsdl7.7_3.0_TCSOnlineService/TCSOnlineService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TCSOnlineService30(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TCSOnlineService30(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TCSOnlineService30() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TCSOnlineService30(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TCSOnlineService30(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TCSOnlineService30(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns TCSOnlineServiceV30
     */
    @WebEndpoint(name = "TCSOnlineServicePort")
    public TCSOnlineServiceV30 getTCSOnlineServicePort() {
        return super.getPort(TCSOnlineServicePort, TCSOnlineServiceV30.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TCSOnlineServiceV30
     */
    @WebEndpoint(name = "TCSOnlineServicePort")
    public TCSOnlineServiceV30 getTCSOnlineServicePort(WebServiceFeature... features) {
        return super.getPort(TCSOnlineServicePort, TCSOnlineServiceV30.class, features);
    }
    /**
     *
     * @return
     *     returns TCSOnlineServiceV30
     */
    @WebEndpoint(name = "TCSOnlineServicePort.0")
    public TCSOnlineServiceV30 getTCSOnlineServicePort0() {
        return super.getPort(TCSOnlineServicePort0, TCSOnlineServiceV30.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TCSOnlineServiceV30
     */
    @WebEndpoint(name = "TCSOnlineServicePort.0")
    public TCSOnlineServiceV30 getTCSOnlineServicePort0(WebServiceFeature... features) {
        return super.getPort(TCSOnlineServicePort0, TCSOnlineServiceV30.class, features);
    }

}
