package gov.treas.fms.services.tcsonline_3_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-01-23T19:59:31.343-06:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", name = "TCSOnlineService_v3_0")
@XmlSeeAlso({ObjectFactory.class})
public interface TCSOnlineServiceV30 {

    @WebMethod
    @RequestWrapper(localName = "createForce", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CreateForce")
    @ResponseWrapper(localName = "createForceResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CreateForceResponseType")
    @WebResult(name = "createForceResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.CreateForceResponse createForce(
        @WebParam(name = "createForceRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.CreateForceRequest createForceRequest
    ) throws TCSServiceFault_Exception;

    @WebMethod
    @RequestWrapper(localName = "closeAuthorization", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CloseAuthorization")
    @ResponseWrapper(localName = "closeAuthorizationResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CloseAuthorizationResponseType")
    @WebResult(name = "closeAuthorizationResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.CloseAuthorizationResponse closeAuthorization(
        @WebParam(name = "closeAuthorizationRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.CloseAuthorizationRequest closeAuthorizationRequest
    ) throws TCSServiceFault_Exception;

    @WebMethod
    @RequestWrapper(localName = "completeOnlineCollection", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollection")
    @ResponseWrapper(localName = "completeOnlineCollectionResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollectionResponseType")
    @WebResult(name = "completeOnlineCollectionResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollectionResponse completeOnlineCollection(
        @WebParam(name = "completeOnlineCollectionRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollectionRequest completeOnlineCollectionRequest
    ) throws TCSServiceFault_Exception;

    @WebMethod
    @RequestWrapper(localName = "startOnlineCollection", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.StartOnlineCollection")
    @ResponseWrapper(localName = "startOnlineCollectionResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.StartOnlineCollectionResponseType")
    @WebResult(name = "startOnlineCollectionResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.StartOnlineCollectionResponse startOnlineCollection(
        @WebParam(name = "startOnlineCollectionRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.StartOnlineCollectionRequest startOnlineCollectionRequest
    ) throws TCSServiceFault_Exception;

    @WebMethod
    @RequestWrapper(localName = "completeOnlineCollectionWithDetails", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollectionWithDetails")
    @ResponseWrapper(localName = "completeOnlineCollectionWithDetailsResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollectionWithDetailsResponseType")
    @WebResult(name = "completeOnlineCollectionWithDetailsResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollectionWithDetailsResponse completeOnlineCollectionWithDetails(
        @WebParam(name = "completeOnlineCollectionWithDetailsRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.CompleteOnlineCollectionWithDetailsRequest completeOnlineCollectionWithDetailsRequest
    ) throws TCSServiceFault_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDetails", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.GetDetails")
    @ResponseWrapper(localName = "getDetailsResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.GetDetailsResponseType")
    @WebResult(name = "getDetailsResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.GetDetailsResponse getDetails(
        @WebParam(name = "getDetailsRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.GetDetailsRequest getDetailsRequest
    ) throws TCSServiceFault_Exception;

    @WebMethod
    @RequestWrapper(localName = "createForceWithDetails", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CreateForceWithDetails")
    @ResponseWrapper(localName = "createForceWithDetailsResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.CreateForceWithDetailsResponseType")
    @WebResult(name = "createForceWithDetailsResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.CreateForceWithDetailsResponse createForceWithDetails(
        @WebParam(name = "createForceWithDetailsRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.CreateForceWithDetailsRequest createForceWithDetailsRequest
    ) throws TCSServiceFault_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPaymentTypes", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.GetPaymentTypes")
    @ResponseWrapper(localName = "getPaymentTypesResponse", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0", className = "gov.treas.fms.services.tcsonline_3_0.GetPaymentTypesResponseType")
    @WebResult(name = "getPaymentTypesResponse", targetNamespace = "")
    public gov.treas.fms.services.tcsonline_3_0.GetPaymentTypesResponse getPaymentTypes(
        @WebParam(name = "getPaymentTypesRequest", targetNamespace = "")
        gov.treas.fms.services.tcsonline_3_0.GetPaymentTypesRequest getPaymentTypesRequest
    ) throws TCSServiceFault_Exception;
}
