
package gov.treas.fms.services.tcsonline_3_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-01-23T19:59:31.301-06:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "TCSServiceFault", targetNamespace = "http://fms.treas.gov/services/tcsonline_3_0")
public class TCSServiceFault_Exception extends Exception {
    
    private gov.treas.fms.services.tcsonline_3_0.TCSServiceFault tcsServiceFault;

    public TCSServiceFault_Exception() {
        super();
    }
    
    public TCSServiceFault_Exception(String message) {
        super(message);
    }
    
    public TCSServiceFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TCSServiceFault_Exception(String message, gov.treas.fms.services.tcsonline_3_0.TCSServiceFault tcsServiceFault) {
        super(message);
        this.tcsServiceFault = tcsServiceFault;
    }

    public TCSServiceFault_Exception(String message, gov.treas.fms.services.tcsonline_3_0.TCSServiceFault tcsServiceFault, Throwable cause) {
        super(message, cause);
        this.tcsServiceFault = tcsServiceFault;
    }

    public gov.treas.fms.services.tcsonline_3_0.TCSServiceFault getFaultInfo() {
        return this.tcsServiceFault;
    }
}
