# Root logger option
#log4j.rootLogger=INFO, stdout, file, RollingAppender,INFO,console
#log4j.rootLogger=stdout,file,RollingAppender,console

log4j.rootLogger=stdout,file,RollingAppender,console

log4j.appender.console=org.apache.log4j.ConsoleAppender


log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
# use a simple message format
log4j.appender.stdout.layout.ConversionPattern=%m%n
#log4j.appender.console.Threshold=ERROR
# Redirect log messages to a log file
#log4j.appender.RollingAppender=org.apache.log4j.DailyRollingFileAppender
#log4j.appender.RollingAppender.File=${jboss.home.dir}/standalone/log/epds.log
#log4j.appender.RollingAppender.DatePattern='.'yyyy-MM-dd
#log4j.appender.RollingAppender.layout=org.apache.log4j.PatternLayout
#log4j.appender.RollingAppender.layout.ConversionPattern=[%p] %d %c %M - %m%n

# LOG4J daily rolling log files configuration
#log4j.rootLogger=INFO, RollingAppender
#log4j.rootLogger=RollingAppender

#log4j.appender.RollingAppender=org.apache.log4j.DailyRollingFileAppender
#log4j.appender.RollingAppender.File=${jboss.home.dir}/standalone/log/epds.log
#log4j.appender.RollingAppender.DatePattern='.'yyyy-MM-dd
#log4j.appender.RollingAppender.layout=org.apache.log4j.PatternLayout
#log4j.appender.RollingAppender.layout.ConversionPattern=[%p] %d %c %M - %m%n
#log4j.appender.RollingAppender.Threshold=INFO

log4j.appender.RollingAppender=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.RollingAppender.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
log4j.appender.RollingAppender.rollingPolicy.ActiveFileName=${jboss.home.dir}/standalone/log/epds.log
log4j.appender.RollingAppender.rollingPolicy.FileNamePattern=${jboss.home.dir}/standalone/log/epds.log.%d{yyyy-MM-dd}.gz
log4j.appender.RollingAppender.layout=org.apache.log4j.PatternLayout
#log4j.appender.RollingAppender.layout.ConversionPattern=%d [%t] %-5p (%F:%L) - %m%n
log4j.appender.RollingAppender.layout.ConversionPattern=[%p] %d %c %M - %m%n
log4j.appender.RollingAppender.Threshold=INFO

#log4j.appender.file=org.apache.log4j.RollingFileAppender
#log4j.appender.file.File=${jboss.home.dir}/standalone/log/epds.log
#log4j.appender.file.MaxFileSize=10MB
#log4j.appender.file.layout=org.apache.log4j.PatternLayout

#uncomment the below options if we need to INFO and trace the sql queries....
#log4j.logger.org.hibernate = WARN
#log4j.logger.org.hibernate = ERROR
#log4j.logger.org.hibernate.SQL=INFO
#log4j.logger.org.hibernate.type=TRACE

#log4j.logger.org.hibernate = WARN
#log4j.logger.org.hibernate = ERROR

log4j.logger.org.hibernate.SQL=OFF
log4j.logger.org.hibernate=INFO

log4j.logger.com.sun.xml.internal.bind = INFO
log4j.logger.com.sun.xml.bind = INFO
log4j.category.org.springframework=INFO
log4j.logger.org.springframework=INFO 
log4j.category.org.springframework.beans.factory=INFO


log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
